name: build and test

on:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            TARGET: linux

    steps:
      - name: 'Download jextract'
        id: jextract
        uses: oracle-actions/setup-java@v1
        with:
          install: false
          uri: https://download.java.net/java/early_access/jextract/1/openjdk-21-jextract+1-2_${{ matrix.TARGET }}-x64_bin.tar.gz

      - name: 'Extract jextract'
        shell: sh
        run: |
          mkdir -p /tmp/jextract
          tar --strip-components=1 -xvf ${{ steps.jextract.outputs.archive }} -C /tmp/jextract
          export PATH=${PATH}:/tmp/jextract/bin

      - name: 'Download JDK 19'
        id: jdk_21
        uses: oracle-actions/setup-java@v1
        with:
            website: oracle.com
            release: 21

      - name: 'Check out repository'
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: make jar
        shell: bash
        run: |
          export PATH=${PATH}:/tmp/jextract/bin
          make jar-src
