name: build and release

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            TARGET: linux

    steps:
      - name: 'Download jextract'
        id: jextract
        uses: oracle-actions/setup-java@v1
        with:
          install: false
          uri: https://download.java.net/java/early_access/jextract/22/5/openjdk-22-jextract+5-33_${{matrix.TARGET}}-x64_bin.tar.gz

      - name: 'Extract jextract'
        shell: sh
        run: |
          mkdir -p /tmp/jextract
          tar --strip-components=1 -xvf ${{ steps.jextract.outputs.archive }} -C /tmp/jextract
          export PATH=${PATH}:/tmp/jextract/bin

      - name: 'Download JDK'
        id: jdk
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 22

      - name: 'Check out repository'
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: version
        id: version
        shell: bash
        run: echo "::set-output name=version::$(date +'%Y.%m.%d-%H')"

      - name: Publish package
        run: |
          export PATH=${PATH}:/tmp/jextract/bin
          make jar-src

      - name: 'make release'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GH_RELEASE_TOKEN }}
          automatic_release_tag: ${{ steps.version.outputs.version }}
          prerelease: false
          title: f1.game C API ${{ steps.version.outputs.version }}
          files: |
            LICENSE
            target/*.jar
